spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/journaldb}
      auto-index-creation: true
  application:
    name: Journal
  main:
    banner-mode: console
  banner:
    location: classpath:my-banner.txt

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.Journal: INFO
