spring:
  data:
    mongodb:
      uri: mongodb+srv://ramanishubh_db_user:Shubh2108@cluster0.664hscx.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  application:
    name: Journal
  main:
    banner-mode: console
  banner:
    location: classpath:my-banner.txt
  devtools:
    restart:
      enabled: false
      poll-interval: 6000
      quiet-period: 500

server:
  port: 8066
